// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRU7YQGEx5m0WUsZpiK7KUX7Ri-du5Wkg',
    appId: '1:641571105178:web:5511cf0511e62c634d3223',
    messagingSenderId: '641571105178',
    projectId: 'scorelivepro-67f37',
    authDomain: 'scorelivepro-67f37.firebaseapp.com',
    storageBucket: 'scorelivepro-67f37.firebasestorage.app',
    measurementId: 'G-RXZQGNCLH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOvSl7-jPmdZ8kN-G5LrrRWGb9yZwyCDI',
    appId: '1:641571105178:android:e7356ebdea86e43e4d3223',
    messagingSenderId: '641571105178',
    projectId: 'scorelivepro-67f37',
    storageBucket: 'scorelivepro-67f37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqqhz7XoWjd8OUTaSTu-YULv8A6woy60c',
    appId: '1:641571105178:ios:00a4d620b66960334d3223',
    messagingSenderId: '641571105178',
    projectId: 'scorelivepro-67f37',
    storageBucket: 'scorelivepro-67f37.firebasestorage.app',
    androidClientId:
        '641571105178-brdjpvqttg4jj0j1nfg1qleh8ka766oi.apps.googleusercontent.com',
    iosBundleId: 'com.scorelivepro.app.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqqhz7XoWjd8OUTaSTu-YULv8A6woy60c',
    appId: '1:641571105178:ios:b67d564eb6f46a4d4d3223',
    messagingSenderId: '641571105178',
    projectId: 'scorelivepro-67f37',
    storageBucket: 'scorelivepro-67f37.firebasestorage.app',
    androidClientId:
        '641571105178-brdjpvqttg4jj0j1nfg1qleh8ka766oi.apps.googleusercontent.com',
    iosBundleId: 'com.scorelivepro.app',
  );
}
